[package]
name = "deep-swarm-plugins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
wasmtime.workspace = true

[dev-dependencies]
wit-component = "0.253.0"

[lints]
workspace = true
